stages:
  - lint
  - test
  - e2e
variables:
  DOCKER_HOST: tcp://docker:2375

golangci_lint:
  stage: lint
  image:
    name: $CI_REGISTRY_GO/lint:latest
    entrypoint: [""]
  tags:
    - go
  script:
    - golangci-lint run --color always --timeout 120s

lint-commit-msg:
  stage: lint
  image:
    name: $CI_REGISTRY_GO/check-commit:latest
    entrypoint: [""]
  tags:
    - go
  script:
    - go run /check.go

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  image:
    name: $CI_REGISTRY_GO/golang:1.15
    entrypoint: [ "" ]
  before_script:
    - mkdir -p .go
  cache:
    paths:
      - .go/pkg/mod/

build:
  extends: .go-cache
  stage: lint
  tags:
    - go
  before_script:
    - mkdir -p .go
  script:
    - go build

test:
  extends: .go-cache
  stage: test
  image:
    name: $CI_REGISTRY_GO/golang:1.15
    entrypoint: [""]
  tags:
    - go
  script:
    - go test ./...

.e2e:
  stage: e2e
  extends: .go-cache
  image:
    name: $CI_REGISTRY_GO/docker:stable
    entrypoint: [ "" ]
  services:
    - name: $CI_REGISTRY_GO/docker:18.09.7-dind
      alias: docker
  tags:
    - go
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY_GO
    - docker pull $CI_REGISTRY_GO/client-native:$HAPROXY_VERSION
    - docker image tag $CI_REGISTRY_GO/client-native:$HAPROXY_VERSION test_env
    - docker build -f e2e/Dockerfile -t client-native-test .
  script:
    - docker run --entrypoint "go" client-native-test test -tags integration ./...

HAProxy_2_1:
  extends: .e2e
  variables:
    HAPROXY_VERSION: "2.1"
HAProxy_2_2:
  extends: .e2e
  variables:
    HAPROXY_VERSION: "2.2"
HAProxy_2_3:
  extends: .e2e
  variables:
    HAPROXY_VERSION: "2.3"
